GET http://localhost:5000/users

###
POST  http://localhost:5000/user
Content-Type: application/json

{
  "name": "Galih Pratama",
  "email": "galih@mail.com",
  "password": "secret",
  "confirm_password": "secret"
}