GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJOYW1lIjoiR2FsaWggUHJhdGFtYSIsInVzZXJFbWFpbCI6ImdhbGloQG1haWwuY29tIiwiaWF0IjoxNjY2ODUyMDI0LCJleHAiOjE2NjY4NTIwNDR9.huNZQ6chMZ3qz-JrCe2z_ozC5M8GXcoqCrT2smeUzds


###
POST  http://localhost:5000/register
Content-Type: application/json

{
  "name": "Galih Pratama",
  "email": "galih@mail.com",
  "password": "secret",
  "confirm_password": "secret"
}


###
POST  http://localhost:5000/login
Content-Type: application/json

{
  "email": "galih@mail.com",
  "password": "secret"
}


###
GET http://localhost:5000/refresh_token


###
DELETE http://localhost:5000/logout