GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJHYWxpaCBQcmF0YW1hIiwiZW1haWwiOiJnYWxpaEBtYWlsLmNvbSIsImlhdCI6MTY2NjY4MTIyMCwiZXhwIjoxNjY2NjgxMjQwfQ.ERwigiROPtkQqhBvlIK8D7o2xufQkpOFI2GHz4leuCU

###
POST  http://localhost:5000/user
Content-Type: application/json

{
  "name": "Galih Pratama",
  "email": "galih@mail.com",
  "password": "secret",
  "confirm_password": "secret"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
  "email": "galih@mail.com",
  "password": "secret"
}

###
GET http://localhost:5000/refresh_token